### PR TITLE
Laravel 8 support

### LINKED ISSUE #67: Laravel 8.x Compatibility
It looks like Laravel 8.x is not compatibile (yet). 

Is this something that is on the roadmap?

### PR DESCRIPTION
**Pull request by Pr3d4dor**
This pull request adds Laravel 8 support.

---
Closes #67

### CODE REVIEW

**Comment by Pr3d4dor** [comment]
I dont know why Scrutinizer failed.

**Comment by jltxwesley** [comment]
Any update on this?

**Comment by ImJustToNy** [comment]
@Pr3d4dor  I believe its misconfigured, since commits on master are failing too

**Comment by Pr3d4dor** [comment]
@ImJustToNy Yeah, I think it is misconfigured too.

**Comment by Pr3d4dor** [comment]
@mpociot Sorry to bother you, but do you have any updates on this?

**Comment by daryledesilva** [comment]
up

**Comment by mpociot** [comment]
Thanks for this, sorry that it took a bit :)

**Pull request merged**
