### PR TITLE
Assert response is html before injecting alert or console outputs

### PR DESCRIPTION
**Pull request by stevelacey**
The script tags were getting injected into JSON responses (and obscurely breaking my tests) 🙃️

### CODE REVIEW

**Comment by erikverbeek** [comment]
I just had this break an API call as well. The added script tag appended to the JSON string turns the whole thing to `null`  once it gets parsed in the frond-end.

**Comment by stevelacey** [comment]
@mpociot ping 😄☝️

**Comment by stevelacey** [comment]
@mpociot and tag a release 😄🙏🏼 thanks!

**Comment by mpociot** [comment]
done

**Comment by stevelacey** [comment]
🙌

**Pull request merged**
