### PR TITLE
Laravel 7 Support

### PR DESCRIPTION
**Pull request by matthewnessworthy**

### CODE REVIEW

**Comment by matthewnessworthy** [comment]
@mpociot please can you take a look when you have a moment

**Comment by matthewnessworthy** [comment]
@mpociot 👋

**Comment by intellow** [comment]
@matthewnessworthy You need to update orchestra/testbench to include up to version 5.0. This ensures the test suite is run with Laravel 7.

**Comment by matthewnessworthy** [comment]
@intellow all the tests pass, why would additional changes be needed?

**Comment by intellow** [comment]
> @intellow all the tests pass, why would additional changes be needed?

The version of orchestra/testbench defines what version of Laravel is used when the tests are run. Right now, with the version set to 3.6.*, the test suite is running (and passing) on a Laravel 5.6 app. We need to make sure the tests still pass when running on a Laravel 7 app.

**Comment by matthewnessworthy** [comment]
@intellow 
i've made some updates to test various versions of laravel against various versions of php
all seems to be working fine, but Scrutinizer appears to be failing with no error message

**Comment by mpociot** [comment]
Thank you!

**Pull request merged**
