### PR TITLE
Support for multiple outputs

### PR DESCRIPTION
**Pull request by Braunson**
Providing legacy support for multiple outputs

- Support multiple outputs

Referencing issue #7

### CODE REVIEW

**Comment by tvbeek** [comment]
@Braunson it isn't forcing but the default, I think that is a different. But on the end it is a choice that @mpociot need to make.

**Comment by mpociot** [comment]
I really like the ability to have multiple output types, but I would like to stick to using the`APP_DEBUG` setting as a fallback value. Could you modify your PR / send a new one, only with the multiple output changes?

**Comment by Braunson** [comment]
@mpociot Updated the PR code.

**Comment by mpociot** [comment]
Thank you

**Pull request merged**
